name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: |
            if [ "${{ github.event.inputs.name }}" != "" ]; then
                echo "Hello ${{ github.event.inputs.name }}"
            else
                echo "Hello World!!"
            fi